apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgAbRK3cdkLz2aS9TRrDIyZoYxxVShVX7A9zUXeKapv6+/36AdfazHLW5in+ysErq/mB6BLMkYHzoAy3eDQcDf1wHcpY4JHujXbFfmZfNOlPnxMkBaEJF6YVUJ4ISW5kT1NkHc8lr4zexP8+EB6GhvkmFlA4IaLMtMmUrWD1QFcvzF1wHp+2vRXFR0w6LtHIrmwXUmnsG9F6NkP+elvuUJDuSY2be4GqBoWXPZwsBjk5BlJMIkAW+GFO24kqXHgh2ymzQua9WTA3Str3+xKSj4KTGihCaTS+dRacBAGlxEp4piQRuQAbvgd24QJB5oRx/+158/O7MiPVZKVr/L3Pl7VwlnuMjDYDGnyFkq6bZP4hbontb9sB+Q8zy5xNxTUC1LAhf7SsRQ737rdeq1S/Ti20O38uQB7YoKTecHLxdbggbJW7SSlNrTUwSKMe8KTj+BH7o08F6k4IWbhd9uDgLvXQzoloBCGX1DG1idc8x8N5syTM1o2OCUHG9pbqbz2nTP6mfTpQWMPgweOracfpu3chPeRnr/2/ZzFkxkpz/QydkTQSNU0AG1CXkphpWyR9bR1eLZIzzBLzl22rgmDmEiVbDiwc+9uZahKukE6Tk7HGr70GUk0G1UKab6ei9GNN05tatXeaEgMwaRSMvoNMHrTnyAOBbg69CRqYctC0gkyCl8hvOrC7oO/8tpfSiXf6t2QRruY6fJ9qiXvJdonPKK3en2NminFz8SWFvxa/SxChzhTKVQ0OJvEPbo3Myt3+Uxh1+iO/BYUYy0iAhjVAsNDgQWvHnF9LR+3ZY0Q2iYZrVoiTIvs8sjc9x7MTjbqwAoxovKp/ySScTGdTK4WNvJgjXn4gcVHVn8fqUjE6klbHffg+R5M87YbaYt8zpEFy5wBsyJJW8ln/Ujqkz/bohff3yNPTIHLQUeeAbCdSDt6d5FSXBoXYyDMpy1au4kzJVPtTKLXNwq8s3bQCEg13WrY5UE1aVqvb0iIKzTmW/wMurI02HYspj1HFE8h6U/hlyWi/cD76Ct5+LOc1gVLu/24+pwi0tUEbbKTA8TAyX5tfGOY7KoZI8lMog5n6M/7pMmLJe+tfqiZDTt9YMe/+fZElB8inNubHYfBkUGXx+LnZ3qDiwrp1tW+X/WJ/wvqX95267/4LHfdzc642iuRsu1QGzANcU/ebAXahpaIvDtsqS5+HqovilVr+npZAisYfm4IawNv/Vn1+B8t+NpP2ZGQvf0DnwYgEIqNIaHo40Ve8vh9jY90H5SOGRSWdk3SHPbXasgtjSfqO+KrGO7HfZixlnc4zuaARV0/1tWqxjb6+Y6g55c/TGwvuW0iRTssymsnt
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

